services:
- name: Norbtest
  url: https://news.ycombinator.com

checks:
- name: HTTP Test
  service: Norbtest
  checkrunner: http
  severity: Error
  vars:
    url: https://news.ycombinator.com

- name: HTTP Test 2
  service: Norbtest
  checkrunner: http
  severity: Error
  vars:
    url: https://news.ycombinator.com
    expected: [400]

